MyAspIdentity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyAspIdentity.Models;

namespace MyAspIdentity.Controllers
{
    public class HomeController : Controller
    {
        private readonly UserManager<MideUser> userManager;

        public HomeController(UserManager<MideUser> userManager)
        {
            this.userManager = userManager;
        }

        private Task<MideUser> CurrentUser => userManager.FindByNameAsync(HttpContext.User.Identity.Name);

        [Authorize]
        public IActionResult Index()
        {
            return View(GetData(nameof(Index)));
        }
        [Authorize(Roles = "Admin")]
        public IActionResult OtherAction() => View("Index", GetData(nameof(OtherAction)));
        private Dictionary<string, object> GetData(string actionName) =>
            new Dictionary<string, object>
            {
                ["Action"] = actionName,
                ["User"] = HttpContext.User.Identity.Name,
                ["Authenticated"] = HttpContext.User.Identity.IsAuthenticated,
                ["Auth Type"] = HttpContext.User.Identity.AuthenticationType,
                ["In Users Role"] = HttpContext.User.IsInRole("Admin"),
                ["City"]= CurrentUser.Result.City,
                ["Qualification"]= CurrentUser.Result.Qualification
            };
        [Authorize]
        public async Task<IActionResult> UserProps()
        {
            ViewBag.City = new SelectList(Enum.GetNames(typeof(Cities)));
            ViewBag.Qualification = new SelectList(Enum.GetNames(typeof(QualificationLevels)));
            return View(await CurrentUser);
        }    
        
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UserProps([Required] Cities city, [Required] QualificationLevels qualification)
        {
            if (ModelState.IsValid)
            {
                MideUser user= await CurrentUser;
                user.City = city;
                user.Qualification = qualification;
                await userManager.UpdateAsync(user);
                return RedirectToAction("Index");
            }

            return View(await CurrentUser);
        }
    }
}

MyAspIdentity/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyAspIdentity.Models;

namespace MyAspIdentity.Controllers
{
    [Authorize]
    public class MyAccountController : Controller
    {
        private readonly UserManager<MideUser> userManager;
        private readonly SignInManager<MideUser> signInManager;

        public MyAccountController(UserManager<MideUser> usrMgr, SignInManager<MideUser> signInMgr)
        {
            this.userManager = usrMgr;
            this.signInManager = signInMgr;
        }
        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model,string returnUrl)
        {
            if (ModelState.IsValid)
            {
                MideUser user = await userManager.FindByEmailAsync(model.Email);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                   Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, false, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginModel.Email), "Invalid User or Password");
            }

            return View(model);
        }

        public async Task<IActionResult> LogOut()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

MyAspIdentity/Views/Home/Index.cshtml
@model Dictionary<string, object>




@{
    ViewData["Title"] = "Index";
}

<div class="bg-primary m-1 p-1 text-white"><h4>User Detail</h4></div>


<table class="table table-sm table-bordered m-1 p-1">
    @foreach (var kvp in Model)
    {
        <tr>
            <th>@kvp.Key</th>
            <td> @kvp.Value</td>

        </tr>
    }
    @if (User?.Identity?.IsAuthenticated ?? false)
    {
        <a asp-controller="MyAccount" asp-action="LogOut" class="btn btn-danger">Logout</a>
    }
    else {
    <a asp-controller="MyAccount" asp-action="Login" class="btn btn-danger">LogIn</a>
    }
</table>

MyAspIdentity/Views/Home/UserProps.cshtml
@model MideUser
<div class="bg-primary m-1 p-1 text-white"><h4>@Model.UserName</h4></div>
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-action="UserProps" method="post">
    <div class="form-group">
        <label asp-for="City"></label>
        <select asp-for="City" class="form-control"
                asp-items="@ViewBag.City">
            <option disabled selected value="">Select a City</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Qualification"></label>
        <select asp-for="Qualification" class="form-control"
                asp-items="@ViewBag.Qualification">
            <option disabled selected value="">Select a Qualification</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>